version: "3.9"

services:

  postgis:
    image: postgis/postgis
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  caddy:
    env_file: ../.env
    image: caddy/caddy
    container_name: "caddy"
    hostname: "caddy"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./static:/var/static/

  django:
    restart: unless-stopped
    env_file: ../.env
    expose:
      - 8000
    build:
      context: ../
      dockerfile: deploy/django/Dockerfile
    command: sh -c "python manage.py wait_for_db &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DB_HOST=postgis
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - postgis
    volumes:
      - ./static:/vol/web/static

volumes:
  dev-db-data: